// CLASSES

// #1 STUDENT CAN BUILD A CLASS.



// #2 STUDENT CAN BUILD A CLASS WITH A CONSTRUCTOR METHOD.



// #3 STUDENT CAN USE THE THIS KEYWORD IN THE CONSTRUCTOR TO ADD PROPERTIES TO AN OBJECT.



// #4 STUDENT CAN CREATE AN OBJECT WITH BASIC PROPERTIES FROM A CLASS WITH A CONSTRUCTOR UTILIZING THE NEW KEYWORD AND INVOKING THE CLASS.



// #5 STUDENT CAN USE PARAMETERS IN THE CONSTRUCTOR METHOD TO ASSIGN PROPERTY VALUES.



// #6 STUDENT CAN PASS ARGUMENTS TO THE INVOKED CLASS WHEN THE OBJECT IS CREATED.



// #7 STUDENT CAN CREATE PROTOTYPE METHODS ON THE CLASS.



// #8 STUDENT CAN ALTER THE OBJECT VALUES FROM A PROTOTYPE METHOD BY USING THE THIS KEYWORD.


