// OBJECTS

// #1 STUDENT CAN USE DELETE TO DELETE AN OBJECT PROPERTY.



// #2 STUDENT CAN USE A FOR IN LOOP TO ACCESS PROPERTY NAMES AND PROPERTY VALUES ON AN OBJECT.



// #3 STUDENT CAN USE OBJECT.ASSIGN() TO CREATE A NEW OBJECT.



// #4 STUDENT CAN USE OBJECT DESTRUCTURING TO CREATE NEW VARIABLES FROM AN OBJECT.


